apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-nginx
  labels:
    app: gitops-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Service
metadata:
  name: gitops-nginx
  labels:
    app: gitops-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    target port: 80
  selector:
    app: gitopx-nginx
