machine:
  network:
    hostname: talos-server2
    interfaces:
      - interface: enp1s0
        dhcp: false
        addresses:
          - 10.10.20.10/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.10.20.1
    nameservers:
      - 192.168.1.40
